### ISSUE TITLE
Fix code so file.check_hash module runs

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/sqlplus-formula#12]
Need to fix `map.jinja` and `init.sls` so supplied MD5sums are verified.  This is a regression introduced by PR #11 
```
  dl:
    skip_hashcheck: False
```

```
{% if sqlplus.dl.skip_hashcheck in ('None', 'False', 'false', 'FALSE') %}
  module.run:
    - name: file.check_hash
    - path: '{{ sqlplus.tmpdir }}/{{ pkg }}.{{ sqlplus.dl.suffix }}'
    - file_hash: {{ sqlplus.oracle.md5[ pkg ] }}
    - onchanges:
      - cmd: sqlplus-extract-{{ pkg }}
    - require_in:
      - archive: sqlplus-extract-{{ pkg }}
  {% endif %}
```
